### PR TITLE
feat(IAM Identity): Add support for IAM enterprise

### PR DESCRIPTION
**Pull request by michaelbeck**
## PR summary
Added support for IAM enterprise feature. Enterprise admins can create templates for account settings and trusted profiles and assign them to accounts and account groups in the enterprise.

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  
SDK adopters will be able to work with IAM enterprise feature.

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information
API definition: [Staging](https://test.cloud.ibm.com/apidocs/iam-identity-token-api#list-profile-templates)

Test information:

Integration Tests:
```
==================================================== test session starts ====================================================
platform win32 -- Python 3.10.11, pytest-7.4.0, pluggy-1.2.0
rootdir: D:\BlueMix\repos\platform-services-python-sdk
collected 87 items

test\integration\test_iam_identity_v1.py ............................................................................. [ 88%]
..........                                                                                                             [100%]

============================================== 87 passed in 701.43s (0:11:41) ===============================================
```

Examples:
```
==================================================== test session starts ====================================================
platform win32 -- Python 3.10.11, pytest-7.4.0, pluggy-1.2.0
rootdir: D:\BlueMix\repos\platform-services-python-sdk
collected 68 items

examples\test_iam_identity_v1_examples.py ....................................................................         [100%]

============================================== 68 passed in 657.28s (0:10:57) ===============================================
```

### CODE REVIEW

**Comment by padamstx** [comment]
@michaelbeck looks like the travis build failed the lint check step.
Be sure to follow the instructions in https://github.com/IBM/platform-services-python-sdk/blob/main/update_service.md when updating a service.

**Review by padamstx — CHANGES_REQUESTED** [review]
Changes look good... just need to fix the lint errors.

**Comment by michaelbeck** [comment]
> @michaelbeck looks like the travis build failed the lint check step. Be sure to follow the instructions in https://github.com/IBM/platform-services-python-sdk/blob/main/update_service.md when updating a service.

I tried to follow the steps but again these were referencing an .sh file which would not run under Windows. Please make sure your instructions are valid/working for all developers.

**Comment by pyrooka** [comment]
Hi @michaelbeck!
> Also when I try to run the command from the .sh file, it will respond with No module named pylint. After running pip3 install pylint the linter woked. So please include this with your installation instructions.

If you look at the documentation, the last command in the "Initial project setup" is `make all` which installs all the required dependencies, so if you have run that you shouldn't see any dependency issues.

I think the main problem here is that you are using Windows which is really different from Linux/macOS - what most developers use. Do you have [WSL](https://learn.microsoft.com/en-us/windows/wsl/) installed by any chance? You might want to give it a try, because I think the compatibility and the whole experience would be much better.

**Comment by michaelbeck** [comment]
> Hi @michaelbeck!
> 
> > Also when I try to run the command from the .sh file, it will respond with No module named pylint. After running pip3 install pylint the linter woked. So please include this with your installation instructions.
> 
> If you look at the documentation, the last command in the "Initial project setup" is `make all` which installs all the required dependencies, so if you have run that you shouldn't see any dependency issues.
> 
> I think the main problem here is that you are using Windows which is really different from Linux/macOS - what most developers use. Do you have [WSL](https://learn.microsoft.com/en-us/windows/wsl/) installed by any chance? You might want to give it a try, because I think the compatibility and the whole experience would be much better.

Exactly, `make all` does not work on Windows. And no, I don't have WSL running. You expect teams to support SDK and Terraform generation, that means teams can expect you to support Windows, which is a viable OS in IBM. Fine for me to setup WSL but then please give advice to do so and clear guidance how to.

**Comment by pyrooka** [comment]
Well, when I see an instruction that says "let's use X" and X doesn't work in/support my environment I'd assume that I have to use somethings else that X supports. I think using WSL/Docker/VM is a totally valid scenario. Maybe we can mention this in the docs, we'll discuss.

**Review by padamstx — APPROVED** [review]
Lint errors are fixed and a small change to .travis.yml allowed the Travis build to run clean (there appears to be a problem with the Travis jammy build image which prevents builds from running `sudo api-get update` to update the OS during the build.

**Pull request merged**
