### PR TITLE
fix(IAM Policy Management): remove `options` property from PolicyAssignment

### PR DESCRIPTION
**Pull request by siddhuvarma1997**
## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by siddhuvarma1997** [comment]
Integration tests:
image

**Review by pyrooka — APPROVED** [review]
Looks good, but please sign the CLA! And please attach the result of the example tests too.

**Comment by siddhuvarma1997** [comment]
example tests:
image

**Comment by pyrooka** [comment]
@siddhuvarma1997 @siddhualluri you both must sign the CLA before we can merge this PR. All you need to do is open the link the following comment and click on the button: https://github.com/IBM/platform-services-python-sdk/pull/262#issuecomment-2200746828

**Pull request merged**
