### PR TITLE
fix(Enterprise Management): add options property to create_account payload

### PR DESCRIPTION
**Pull request by namratabhadauriya**
## PR summary
add options property to create_account payload

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by padamstx** [comment]
Just a reminder that we need to re-gen the SDK code with the latest version of the generator (3.87.0).
Also, be sure to run `make lint` (and fix any lint errors by running `make lint-fix` or making manual changes as needed) prior to pushing your changes

**Review by padamstx — APPROVED** [review]
LGTM

**Comment by namratabhadauriya** [comment]
image

**Pull request merged**
