### PR TITLE
feat (IAM Access Groups): Enable search during list groups

### PR DESCRIPTION
**Pull request by hariarla**
## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by hariarla** [comment]
image

**Comment by hariarla** [comment]
Example tests:
image

**Comment by hariarla** [comment]
@padamstx Kindly approve and merge this PR at the earliest.

**Review by padamstx — APPROVED** [review]
LGTM

**Pull request merged**
