### PR TITLE
feat(Resource Controller): add "onetime_credentials" property in ResourceInstance and ResourceKey schemas

### PR DESCRIPTION
**Pull request by swadhin1515**
…nce and ResourceKey schema

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by pyrooka — CHANGES_REQUESTED** [review]
It seems something has been messed up in your git history, because there is a change in the `CHANGELOG.md` that shouldn't be here and the change in the service (`resource_controller_v2.py`) is unusually big. Please make sure that your git history is clean and only include the necessary changes.

**Comment by swadhin1515** [comment]
[output_examples.txt](https://github.com/user-attachments/files/16156935/output_examples.txt)
[output_integration.txt](https://github.com/user-attachments/files/16156936/output_integration.txt)
[output_make_all.txt](https://github.com/user-attachments/files/16156937/output_make_all.txt)

**Comment by pyrooka** [comment]
@swadhin1515 Can we close this PR in favor of #263?

**Comment by swadhin1515** [comment]
Yes sure , we can close this PR .

**Pull request closed without merging**
